REM ------------------------------------------------------------
SET /a COUNTER_EXPORT=%COUNTER_EXPORT% + 1
SET OUTPUT_FILENAME="{OUTPUT_FILENAME}"
SET OUTPUT_PATH="{OUTPUT_PATH}"
SET EXPORT_TYPE={EXPORT_TYPE}
SET PARAM1={PARAM1}
SET PARAM2={PARAM2}
SET PARAM3={PARAM3}
SET PARAM4={PARAM4}
SET CMD_LINE={CMD_LINE}
CALL :GENERATE-EXPORT
CALL :RESET_ERROR
if exist %OUTPUT_FILENAME% (
    @ECHO: No need to create
) else (
    {CMD_LINE}
    TIMEOUT /T 3 /NOBREAK
)
